export const STAGES_CONFIG = [
  {
    id: 1,
    title: 'Fundamentos',
    subtitle: 'Bitcoin desde cero',
    description: '¿Qué es Bitcoin? ¿Quién es Satoshi? ¿Por qué Bitcoin?',
    color: '#F7931A',
    colorGradient: 'from-orange-500 to-amber-500',
    lessons: [
      { id: '1-1', type: 'lesson', title: '¿Qué es Bitcoin?' },
      { id: '1-2', type: 'reading', title: '¿Quién es Satoshi Nakamoto?' },
      { id: '1-3', type: 'lesson', title: '¿Por qué Bitcoin y no otra crypto?' },
      { id: '1-4', type: 'reading', title: '¿Cómo funciona la blockchain?' },
      { id: '1-exam', type: 'exam', title: 'Examen Final de Etapa' },
      { id: '1-chest', type: 'chest', title: 'Cofre de Recompensa' },
    ],
    badge: 'Mente Abierta',
    unlocked: true,
  },
  {
    id: 2,
    title: 'Seguridad Primero',
    subtitle: 'Protege tu Bitcoin',
    description: 'Custodia, seed phrases, hardware wallets',
    color: '#3B82F6',
    colorGradient: 'from-blue-500 to-blue-600',
    lessons: [
      { id: '2-1', type: 'lesson', title: '¿Qué es la custodia?' },
      { id: '2-2', type: 'reading', title: 'Self-custody vs exchange' },
      { id: '2-3', type: 'lesson', title: '¿Qué es una frase secreta (seed phrase)?' },
      { id: '2-4', type: 'lesson', title: 'Cómo proteger tu frase secreta' },
      { id: '2-5', type: 'reading', title: '¿Qué es una hardware wallet?' },
      { id: '2-exam', type: 'exam', title: 'Examen Final de Etapa' },
      { id: '2-chest', type: 'chest', title: 'Cofre de Recompensa' },
    ],
    badge: 'Guardián',
    unlocked: false,
  },
  {
    id: 3,
    title: 'Tu Primera Wallet',
    subtitle: 'Manos a la obra',
    description: 'Crea tu wallet, direcciones, recibe sats',
    color: '#EAB308',
    colorGradient: 'from-yellow-500 to-amber-500',
    lessons: [
      { id: '3-1', type: 'reading', title: 'Tipos de wallets' },
      { id: '3-2', type: 'simulator', title: 'Crea tu primera wallet' },
      { id: '3-3', type: 'lesson', title: '¿Qué es una dirección Bitcoin?' },
      { id: '3-4', type: 'simulator', title: 'Recibe tus primeros sats' },
      { id: '3-exam', type: 'exam', title: 'Examen Final de Etapa' },
      { id: '3-chest', type: 'chest', title: 'Cofre de Recompensa' },
    ],
    badge: 'Primer Paso',
    unlocked: false,
  },
  {
    id: 4,
    title: 'Transacciones',
    subtitle: 'Envía y recibe',
    description: 'Fees, mempool, confirmaciones',
    color: '#22C55E',
    colorGradient: 'from-green-500 to-emerald-500',
    lessons: [
      { id: '4-1', type: 'lesson', title: '¿Qué son las comisiones (fees)?' },
      { id: '4-2', type: 'reading', title: '¿Qué es el mempool?' },
      { id: '4-3', type: 'simulator', title: 'Envía una transacción' },
      { id: '4-4', type: 'lesson', title: '¿Qué son las confirmaciones?' },
      { id: '4-exam', type: 'exam', title: 'Examen Final de Etapa' },
      { id: '4-chest', type: 'chest', title: 'Cofre de Recompensa' },
    ],
    badge: 'Hodler Novato',
    unlocked: false,
  },
  {
    id: 5,
    title: 'Exchanges CEX',
    subtitle: 'Compra Bitcoin',
    description: 'KYC, fondear cuenta, comprar, retirar',
    color: '#06B6D4',
    colorGradient: 'from-cyan-500 to-cyan-600',
    lessons: [
      { id: '5-1', type: 'lesson', title: '¿Qué es un exchange?' },
      { id: '5-2', type: 'reading', title: 'KYC y registro' },
      { id: '5-3', type: 'lesson', title: 'Fondear tu cuenta' },
      { id: '5-4', type: 'lesson', title: 'Comprar Bitcoin' },
      { id: '5-5', type: 'simulator', title: 'Retirar a tu wallet' },
      { id: '5-exam', type: 'exam', title: 'Examen Final de Etapa' },
      { id: '5-chest', type: 'chest', title: 'Cofre de Recompensa' },
    ],
    badge: 'Trader Básico',
    unlocked: false,
  },
  {
    id: 6,
    title: 'Lightning Network',
    subtitle: 'Pagos instantáneos',
    description: 'Canales, pagar y recibir con Lightning',
    color: '#FACC15',
    colorGradient: 'from-yellow-400 to-yellow-500',
    lessons: [
      { id: '6-1', type: 'lesson', title: '¿Qué es Lightning Network?' },
      { id: '6-2', type: 'reading', title: '¿Cómo funciona un canal?' },
      { id: '6-3', type: 'simulator', title: 'Pagar con Lightning' },
      { id: '6-4', type: 'simulator', title: 'Recibir con Lightning' },
      { id: '6-exam', type: 'exam', title: 'Examen Final de Etapa' },
      { id: '6-chest', type: 'chest', title: 'Cofre de Recompensa' },
    ],
    badge: 'Lightning Fast',
    unlocked: false,
  },
  {
    id: 7,
    title: 'DEX y Swaps',
    subtitle: 'Descentralizado',
    description: 'CEX vs DEX, swaps, slippage',
    color: '#A855F7',
    colorGradient: 'from-purple-500 to-purple-600',
    lessons: [
      { id: '7-1', type: 'lesson', title: 'CEX vs DEX — ¿cuál es la diferencia?' },
      { id: '7-2', type: 'reading', title: '¿Qué es un swap?' },
      { id: '7-3', type: 'lesson', title: 'Comisiones y slippage' },
      { id: '7-4', type: 'simulator', title: 'Haz tu primer swap' },
      { id: '7-exam', type: 'exam', title: 'Examen Final de Etapa' },
      { id: '7-chest', type: 'chest', title: 'Cofre de Recompensa' },
    ],
    badge: 'DeFi Explorer',
    unlocked: false,
  },
  {
    id: 8,
    title: 'Liquidez y DeFi',
    subtitle: 'Nivel avanzado',
    description: 'Pools, LP tokens, pérdida impermanente',
    color: '#EF4444',
    colorGradient: 'from-red-500 to-red-600',
    lessons: [
      { id: '8-1', type: 'lesson', title: '¿Qué es un pool de liquidez?' },
      { id: '8-2', type: 'reading', title: '¿Qué son los LP tokens?' },
      { id: '8-3', type: 'simulator', title: 'Proveer liquidez' },
      { id: '8-4', type: 'lesson', title: 'Riesgos — Pérdida Impermanente' },
      { id: '8-exam', type: 'exam', title: 'Examen Final de Etapa' },
      { id: '8-chest', type: 'chest', title: 'Cofre de Recompensa' },
    ],
    badge: 'Liquidity Master',
    unlocked: false,
  },
] as const

export const POINTS_SYSTEM = {
  lessonComplete: 5,
  simulatorComplete: 10,
  examCorrectAnswer: 10,
  examOpenAnswer: { min: 10, max: 25 },
  examPerfectScore: 50,
  stageComplete: 100,
  streak7Days: 75,
  streak30Days: 300,
} as const

export const LEADERBOARD_MOCK = [
  { rank: 1, name: 'CryptoAbuela', points: 2840, stage: 8, streak: 32, badges: 8 },
  { rank: 2, name: 'SatoshiFanMX', points: 2650, stage: 7, streak: 28, badges: 7 },
  { rank: 3, name: 'BitcoinNovato', points: 2420, stage: 6, streak: 21, badges: 6 },
  { rank: 4, name: 'HodlerPro', points: 2180, stage: 6, streak: 15, badges: 6 },
  { rank: 5, name: 'LightningKid', points: 1950, stage: 5, streak: 14, badges: 5 },
]
